openapi: 3.2.0
info:
  title: Testkube Config API
  description: Testkube provides a Kubernetes-native framework for test definition, execution and results
  contact:
    email: contact@testkube.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
tags:
- name: Config
paths:
  /config:
    patch:
      tags:
      - Config
      summary: Update config
      description: Updates config in cluster storage state
      operationId: updateConfigKey
      requestBody:
        description: config request body data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      responses:
        200:
          description: update successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        400:
          description: problem with input
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Problem'
        404:
          description: config not found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Problem'
        500:
          description: problem with updating key in cluster storage
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Problem'
    get:
      tags:
      - Config
      summary: Get config
      description: Get config from cluster storage state
      operationId: getConfig
      responses:
        200:
          description: get successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        404:
          description: config not found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Problem'
        500:
          description: problem with getting config from cluster storage
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Problem'
components:
  schemas:
    Problem:
      description: problem response in case of error
      type: object
      properties:
        type:
          type: string
          description: Type contains a URI that identifies the problem type.
          example: https://kubeshop.io/testkube/problems/invalidtestname
        title:
          type: string
          description: Title is a short, human-readable summary of the problem type. This title SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
          example: Invalid test name
        status:
          type: integer
          description: HTTP status code for this occurrence of the problem.
          example: 500
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          example: Your test name can't contain forbidden characters like "}}}" passed
        instance:
          type: string
          description: A URI that identifies the specific occurrence of the problem. This URI may or may not yield further information if de-referenced.
          example: http://10.23.23.123:8088/tests
    Config:
      description: Testkube API config data structure
      type: object
      required:
      - id
      - clusterId
      - enableTelemetry
      properties:
        id:
          type: string
        clusterId:
          type: string
        enableTelemetry:
          type: boolean
externalDocs:
  description: Find out more about Testkube
  url: https://testkube.kubeshop.io/
