openapi: 3.2.0
info:
  title: Testkube Keymap API
  description: Testkube provides a Kubernetes-native framework for test definition, execution and results
  contact:
    email: contact@testkube.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
tags:
- name: keymap
  description: Keymap for fields in a form
paths:
  /keymap/triggers:
    get:
      tags:
      - keymap
      summary: Test triggers keymap
      description: Returns a keymap (supported/allowed fields) for the test trigger UI screen
      operationId: getKeyMap
      responses:
        200:
          description: successful get operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestTriggerKeyMap'
components:
  schemas:
    TestTriggerKeyMap:
      type: object
      required:
      - resources
      - actions
      - executions
      - events
      - concurrencyPolicies
      properties:
        resources:
          type: array
          items:
            type: string
          description: list of supported values for resources
          example:
          - pod
          - deployment
          - statefulset
          - daemonset
          - service
          - ingress
          - event
          - configmap
        actions:
          type: array
          items:
            type: string
          description: list of supported values for actions
          example:
          - run
        executions:
          type: array
          items:
            type: string
          description: list of supported values for executions
          example:
          - test
          - testsuite
        events:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: mapping between resources and supported events
          example:
            pod:
            - created
            - modified
            - deleted
            deployment:
            - created
            - modified
            - deleted
        conditions:
          type: array
          items:
            type: string
          description: list of supported values for conditions
          example:
          - Available
          - Progressing
        concurrencyPolicies:
          type: array
          items:
            type: string
          description: list of supported values for concurrency policies
          example:
          - allow
          - forbid
          - replace
externalDocs:
  description: Find out more about Testkube
  url: https://testkube.kubeshop.io/
